// <auto-generated />
namespace MarketProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class aey3705 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aey3705));
        
        string IMigrationMetadata.Id
        {
            get { return "202301012008175_aey3705"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
